set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:RGB"

set -sg escape-time 10
set -g repeat-time 600
set -g history-limit 50000

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g focus-events on
set -g set-titles on
set -g set-titles-string "#S / #W"

set -g mouse on

unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind x confirm-before -p "kill pane #P? (y/n)" kill-pane

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind c new-window -c "#{pane_current_path}"
bind -n S-Left  previous-window
bind -n S-Right next-window

setw -g mode-keys vi

bind -n M-Up copy-mode
bind Enter copy-mode

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard"
bind -T copy-mode-vi Escape send -X cancel

unbind -T copy-mode-vi MouseDragEnd1Pane

bind -T copy-mode-vi WheelUpPane send -X -N 5 scroll-up
bind -T copy-mode-vi WheelDownPane send -X -N 5 scroll-down-and-cancel

bind p run "xclip -selection clipboard -o 2>/dev/null | tmux load-buffer - 2>/dev/null; tmux paste-buffer"

bind -n M-h display-popup -E -w 80% -h 70% -T " Ayuda tmux " "$HOME/.tmux/scripts/cheatsheet.sh"
bind h     display-popup -E -w 80% -h 70% -T " Ayuda tmux " "$HOME/.tmux/scripts/cheatsheet.sh"

set -g status on
set -g status-interval 5
set -g status-position bottom
set -g status-justify left
set -g status-style "bg=colour234,fg=colour250"
set -g status-left-length 32
set -g status-right-length 60

set -g status-left "#[fg=colour234,bg=colour39,bold]  #S #[fg=colour39,bg=colour234,nobold] "

setw -g window-status-format "#[fg=colour234,bg=colour238] #[fg=colour250,bg=colour238] #I:#W #[fg=colour238,bg=colour234]"
setw -g window-status-style "fg=colour250,bg=colour238"
setw -g window-status-current-format "#[fg=colour234,bg=colour39] #[fg=colour234,bg=colour39,bold] #I:#W #[fg=colour39,bg=colour234,nobold]"
setw -g window-status-current-style "fg=colour234,bg=colour39,bold"
setw -g window-status-separator " "
setw -g window-status-activity-style "fg=colour214,bg=colour238"

set -g status-right "#[fg=colour238,bg=colour234]#[fg=colour250,bg=colour238] %d/%m  %H:%M #[fg=colour39,bg=colour238]#[fg=colour234,bg=colour39,bold]  #h #[fg=colour39,bg=colour234]"

set -g pane-border-style "fg=colour238"
set -g pane-active-border-style "fg=colour39"
set -g pane-border-status top
set -g pane-border-format " #P: #{pane_current_path} "

set -g message-style "bg=colour39,fg=colour234,bold"
set -g message-command-style "bg=colour39,fg=colour234,bold"
set -g mode-style "bg=colour39,fg=colour234"
set -g clock-mode-colour colour39
